---
classify_query:
  description: >
    Based on the input {query}, classify the query as either a 'research_topic' or an 'academic_question'.
  expected_output: >
    {
      "classification": "research_topic" | "academic_question"
    }
  async_execution: false
  agent: query_classifier
  output_key: classification

process_research_topic:
  description: >
    If the classification is 'research_topic', output a list of credible academic resources based on the {query}.
  expected_output: >
    [
      {
        "title": "Paper Title",
        "authors": ["Author One", "Author Two"],
        "year": 2023,
        "abstract": "A concise summary of the research...",
        "source": "Journal or Conference",
        "citations": "MLA citaion format",
      },
      ...
    ]
  async_execution: false
  agent: senior_data_researcher
  context:
    - classify_query
  output_key: process_research_topic

process_academic_question:
  description: >
    If the classification is 'academic_question', output the answer to the question based on the {query} with academic reasoning.
  expected_output: >
    "A detailed explanation with relevant academic reasoning, including equations, examples, and references where applicable."
  async_execution: false
  agent: academic_helper
  context:
    - classify_query
  output_key: process_academic_question

report_results:
  description: >
    Aggregate and format the final response into a JSON chat-friendly message, using newline breaks and clear structure.
    The output should be a JSON object with the following keys:
    - research_output: The process_research_topic output from the senior_data_researcher if the classification is 'research_topic'.
    - academic_output: The process_academic_question output from the academic_helper if the classification is 'academic_question'.
  expected_output: >
    {
      "response": "[Formatted academic answer or bullet points from research entries]\n"
    }
  async_execution: false
  agent: reporting_analyst
  context:
    - classify_query
    - process_research_topic
    - process_academic_question
