[project]
name = "Backend"
version = "0.1.0"
description = "Backend using crewAI"
requires-python = ">=3.10,<3.13"
dependencies = [
    "crewai[tools]>=0.114.0,<1.0.0",
    "dotenv>=0.9.9",
    "fastapi>=0.115.12",
    "pydantic>=2.11.3",
]
